// ALTLAST: Routen, die heute noch ohne Anmeldung im Code erreichbar sind (Rückfall auf 'demo-user').
// Diese Liste darf nur SCHRUMPFEN: Wird eine Route abgesichert (oder in routePolicy.ts als öffentlich begründet),
// muss ihr Eintrag hier gelöscht und LEGACY_MAX gesenkt werden (der Test erzwingt das). Neue Einträge sind nicht erlaubt.
// Stand 07.10.2026: abgebaut wird in Block b2 (Verwaltungsrouten) und Block d (Rückfall je Modul).
export const LEGACY_MAX = 74

export const LEGACY_ROUTES: string[] = [
  'DELETE /api/companies/[id]',
  'PATCH /api/companies/[id]',
  'GET /api/companies',
  'POST /api/companies',
  'POST /api/contacts/[id]/convert',
  'POST /api/contacts/[id]/touch',
  'DELETE /api/contacts/[id]',
  'PATCH /api/contacts/[id]',
  'GET /api/contacts',
  'POST /api/contacts',
  'DELETE /api/contracts/[id]',
  'PATCH /api/contracts/[id]',
  'GET /api/contracts',
  'POST /api/contracts',
  'DELETE /api/deals/[id]',
  'PATCH /api/deals/[id]',
  'GET /api/deals',
  'POST /api/deals',
  'POST /api/finance/[id]/finalize',
  'DELETE /api/finance/[id]',
  'PUT /api/finance/[id]/status',
  'GET /api/finance/[id]/xrechnung',
  'POST /api/finance/bank-import',
  'POST /api/finance/bank-match',
  'GET /api/finance/bank-txns',
  'DELETE /api/finance/cashbook',
  'GET /api/finance/cashbook',
  'POST /api/finance/cashbook',
  'GET /api/finance/datev',
  'GET /api/finance',
  'POST /api/finance',
  'GET /api/finance/ustva',
  'GET /api/hr/campaigns/[id]/applications',
  'GET /api/hr/campaigns/[id]',
  'PATCH /api/hr/campaigns/[id]',
  'POST /api/hr/campaigns',
  'GET /api/hr',
  'POST /api/hr',
  'POST /api/hr/leave/[id]/approve',
  'POST /api/hr/leave/[id]/reject',
  'GET /api/hr/leave',
  'POST /api/hr/leave',
  'GET /api/hr/stempel',
  'POST /api/hr/stempel',
  'GET /api/hr/timelog',
  'POST /api/hr/timelog',
  'POST /api/marketing/[id]/preview-email',
  'DELETE /api/marketing/[id]',
  'GET /api/marketing/[id]',
  'PATCH /api/marketing/[id]',
  'GET /api/marketing',
  'POST /api/marketing',
  'DELETE /api/notifications/[id]',
  'PATCH /api/notifications/[id]',
  'GET /api/notifications',
  'DELETE /api/pages/[slug]',
  'PUT /api/pages/[slug]',
  'POST /api/pages',
  'PATCH /api/projects/[id]/tasks/[taskId]',
  'POST /api/projects/[id]/tasks',
  'DELETE /api/projects/[id]',
  'PATCH /api/projects/[id]',
  'GET /api/projects',
  'POST /api/projects',
  'POST /api/settings/branding',
  'POST /api/settings/company',
  'GET /api/settings/invoice-template',
  'PUT /api/settings/invoice-template',
  'PATCH /api/shop/products/[id]',
  'POST /api/shop/products',
  'POST /api/support/[id]/comment',
  'PATCH /api/support/[id]',
  'GET /api/support',
  'POST /api/support',
]
